-- PGMQ 1.13.0 table fixup.
--
-- Vendored verbatim from the upstream migration
-- pgmq-extension/sql/pgmq--1.12.0--1.13.0.sql at tag v1.13.0
-- (blob a380ee56e856c5799dcd1486342ce910b96da64e), which is the only part of
-- that file pgbus's upgrade cannot already reproduce: dropping every function
-- and composite type and re-running the target schema recreates functions and
-- types, but never touches an existing table.
--
-- Every file in this directory MUST be idempotent and self-guarded. The
-- upgrade migration applies each fixup between the recorded installed version
-- and the target, and an install whose version was never recorded gets all of
-- them, so a fixup can be replayed against a database that already has it.

-- Partitioned queues: msg_id becomes GENERATED BY DEFAULT AS IDENTITY.
-- pg_partman's partition_data_* tooling moves rows out of the default
-- partition by inserting them with their existing msg_id, which
-- GENERATED ALWAYS refuses. pgmq's own writers never supply msg_id, so this
-- changes nothing for them.
DO $$
DECLARE
    queue_record RECORD;
    qtable TEXT;
BEGIN
    FOR queue_record IN SELECT queue_name FROM pgmq.meta WHERE is_partitioned LOOP
        qtable := pgmq.format_table_name(queue_record.queue_name, 'q');

        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'pgmq'
            AND table_name = qtable
            AND column_name = 'msg_id'
            AND identity_generation = 'ALWAYS'
        ) THEN
            EXECUTE FORMAT('ALTER TABLE pgmq.%I ALTER COLUMN msg_id SET GENERATED BY DEFAULT', qtable);
        END IF;
    END LOOP;
END;
$$;
